dolezel/react-csv-downloader

- src/index.js
> Fixed up click event for mozilla

- src/index.js
> Changing BOM to \ufeff

- example/package.json
- package-lock.json
- package.json
- src/index.js
> Using file-saver for cross-browser support of saving files

- README.md
- src/index.js
- src/lib/csv.js
- src/lib/csv.spec.js
to handle for commas in column values.
default wrap value is "" to maintain backward compatibility,
test cases added.
> add functionality to wrap column value wih any character

- README.md
It should be `--save` not `--save-dev` because this component is not only used during development (like prettier, eslint or other dev tools)
> Component is not a development but productive/live requirement

- README.md
- src/index.tsx
> Compute data on click

- tsconfig.json
> Compiling as commonjs

- src/index.tsx
- src/lib/csv.spec.ts
- src/lib/csv.ts
> Option for new line at end of file

- package-lock.json
- package.json
- src/index.tsx
- src/lib/csv.spec.ts
- src/lib/csv.ts
> Async processing with splitting to chunks

- src/lib/csv.spec.ts
- src/lib/csv.ts
> Fix processing chunks

- src/lib/csv.spec.ts
- src/lib/csv.ts
> Fix processing empty data

- README.md
- src/index.tsx
- src/lib/csv.ts
> Passing props to children

- README.md
- src/index.tsx
Resolves
https://github.com/dolezel/react-csv-downloader/issues/241
> Optional extension

- package.json
- tsconfig-cjs.json
- tsconfig.json
> Proper main/module resolution, using es2015 target

- README.md
- src/index.tsx
> Exporting toCsv function

- src/lib/csv.spec.ts
- src/lib/csv.ts
> Nulls and undefineds should be converted to empty strings

- package.json
> Making engine less restrictive

- package.json
Allow newer npm versions to install the package
> Loosen supported npm version

- README.md
- src/index.tsx
- src/lib/csv.ts
> Handle error and empty data

- src/lib/csv.spec.ts
- src/lib/csv.ts
> Fix duplicate columns
